### ISSUE TITLE
Feature request: allow local-only templates

### ISSUE THREAD

**Issue by KnisterPeter** [marionebl/tipi-cli#11]
Currently tipi load templates from npm (afaik). If you do not want to publish a template or while you develop and test a template it should be possible to just use a template you have e.g. in a folder on your harddisk.

**Comment by KnisterPeter** [comment]
Oh, in the [source](https://github.com/marionebl/tipi-cli/blob/master/packages/tipi-cli/create/get-template.js#L14) there are already local template but it is detected by specify a relative paths.
I did try it with an absolute path.
Could be extended to allow absolute paths as well.

**Comment by marionebl** [comment]
That would be something like 

`isPath = ['/', '.'].includes(name.charAt(0))`

I guess. Would be awesome if you could contribute the needed changes.

**Comment by KnisterPeter** [comment]
Will do so, but I would favor [path-is-absolute](https://www.npmjs.com/package/path-is-absolute) since it will work well on win32 too.
